<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>MDP Shred Usage Writer v1.0.5</AssemblyName>
    <Version>1.0.5</Version>
	<ApplicationIcon>Resources\mdp_logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\BLANK8.xlsx" />
    <None Remove="Resources\mdp_logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\BLANK8.xlsx" />
    <EmbeddedResource Include="Resources\mdp_logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.102.3" />
  </ItemGroup>

</Project>